# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-06-20 16:44:45
"""
import arcpy
from arcpy.ia import *
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def subbasinPopulationAggregation(_Name_UTM30_cubillas=r"C:\Users\Usuario\OneDrive - UNIVERSIDAD DE HUELVA\Granada\TrabajoFM\Genil_ArcGIS_Pascal\Genil_ArcGIS.gdb\{Name}_UTM30_cubillas"):  # subbasin_population_aggregation

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    test_copy = "C:\\Users\\Usuario\\OneDrive - UNIVERSIDAD DE HUELVA\\Granada\\TrabajoFM\\Genil GEO_INFO_POOL\\Input Data\\Population data\\HIPGDAC-ES-v1.0.0\\fgoerlich-HIPGDAC-ES-cd11f21\\HIPGDAC-ES\\test_copy"
    cuenca_cubillas = "cuenca_cubillas"
    cuenca_cubillas_habitantes_1970_2021 = "cuenca_cubillas_habitantes_1970_2021"

    for Raster, Name in #  NOT  IMPLEMENTED(test_copy, "hipgdac_es_100_*.tif", "", "NOT_RECURSIVE"):

        # Process: Project Raster (Project Raster) (management)
        Name = "Raster"
        _Name_UTM30 = fr"C:\Users\Usuario\OneDrive - UNIVERSIDAD DE HUELVA\Granada\TrabajoFM\Genil_ArcGIS_Pascal\Genil_ArcGIS.gdb\{Name}_UTM30"
        arcpy.management.ProjectRaster(in_raster=Raster, out_raster=_Name_UTM30, out_coor_system="PROJCS[\"ETRS_1989_UTM_Zone_30N\",GEOGCS[\"GCS_ETRS_1989\",DATUM[\"D_ETRS_1989\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
        _Name_UTM30 = arcpy.Raster(_Name_UTM30)

        # Process: Clip Raster (Clip Raster) (management)
        arcpy.management.Clip(in_raster=_Name_UTM30, rectangle="438912.500000002 4123462.50012207 470812.5 4158362.50012207", out_raster=_Name_UTM30_cubillas.__str__().format(**locals(),**globals())if isinstance(_Name_UTM30_cubillas, str) else _Name_UTM30_cubillas, in_template_dataset=cuenca_cubillas, clipping_geometry="NONE")
        _Name_UTM30_cubillas = arcpy.Raster(_Name_UTM30_cubillas)

        # Process: Zonal Statistics as Table (Zonal Statistics as Table) (ia)
        _Name_UTM30_cubillas_aggr_subbasin = fr"C:\Users\Usuario\OneDrive - UNIVERSIDAD DE HUELVA\Granada\TrabajoFM\Genil_ArcGIS_Pascal\Genil_ArcGIS.gdb\{Name}_UTM30_cubillas_aggr_subbasin"
        Output_Join_Layer = ""
        arcpy.ia.ZonalStatisticsAsTable(cuenca_cubillas, "", _Name_UTM30_cubillas.__str__().format(**locals(),**globals())if isinstance(_Name_UTM30_cubillas, str) else _Name_UTM30_cubillas, _Name_UTM30_cubillas_aggr_subbasin, "DATA", "SUM", "CURRENT_SLICE", [90], "AUTO_DETECT", "ARITHMETIC", 360, Output_Join_Layer)
        .save(Zonal_Statistics_as_Table)


        # Process: Join Field (Join Field) (management)
        cuenca_cubillas_habitantes_1970_2021_2_ = arcpy.management.JoinField(in_data=cuenca_cubillas_habitantes_1970_2021, in_field="GRIDCODE", join_table=_Name_UTM30_cubillas_aggr_subbasin, join_field="OBJECTID", fields=["SUM"], index_join_fields="NO_INDEXES")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Usuario\\OneDrive - UNIVERSIDAD DE HUELVA\\Granada\\TrabajoFM\\Genil_ArcGIS_Pascal\\Genil_ArcGIS.gdb", workspace="C:\\Users\\Usuario\\OneDrive - UNIVERSIDAD DE HUELVA\\Granada\\TrabajoFM\\Genil_ArcGIS_Pascal\\Genil_ArcGIS.gdb"):
        subbasinPopulationAggregation(*argv[1:])
